Repository lsysophia/MSN-MTDB, pull requests merged in 2020-08, with the labels that each got.

#1 Config file update
  db/config.js
Labels: good first issue

#12 Nz/frontend initial
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/About.jsx
  client/src/components/Footer.jsx
  client/src/components/Header.jsx
  client/src/components/Home.jsx
  client/src/components/Search.jsx
  client/src/components/User.jsx
Labels: good first issue

#10 created the user_series table
  db/migrations/20200820191000-create_user_series_table.sql
Labels: DB

#11 create user_episodes table
  db/migrations/20200829191200-create_user_episodes_table.sql
Labels: DB

#15 User component
  client/src/App.css
  client/src/App.js
  client/src/components/User.jsx
Labels: Frontend

#20 Search component CSS
  client/src/App.css
  client/src/components/Search.jsx
Labels: Frontend

#27 Nz/showpage
  client/src/App.css
  client/src/components/Show.jsx
Labels: Frontend

#29 Nz/model/user series
  client/src/App.js
  controllers/user_series-controller.js
  db/migrations/20200820191000-create_user_shows_table.sql
  db/migrations/20200829191200-create_user_episodes_table.sql
  models/User_series.js
  models/User_shows.js
Labels: DB
